//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEAYA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int TripId { get; set; }
        public int payment_id { get; set; }
        public int TicketCount { get; set; }
        public System.DateTime BookingDate { get; set; }
    
        public virtual Payments Payments { get; set; }
        public virtual Trips Trips { get; set; }
        public virtual Users Users { get; set; }
    }
}
